"""Domain schemas shared across the pipeline."""

from typing import Literal

from pydantic import BaseModel, Field


class Node(BaseModel):
    node_id: str
    node_name: str
    tier: Literal["iot", "edge", "fog", "cloud"]
    node_type: str
    cpu_cores: int
    cpu_freq_ghz: float
    ram_gb: int
    storage_gb: int
    mobility: Literal["static", "mobile"]


class Link(BaseModel):
    link_id: str
    source_node: str
    target_node: str
    link_type: str
    bandwidth_mbps: int
    latency_ms: float
    packet_loss_rate: float
    reliability: float


class Service(BaseModel):
    service_id: str
    name: str
    description: str
    current_node: str
    requirements: dict[str, float] | None = None
    # Downstream service(s) this service sends its output to, forming the
    # application's pipeline as a DAG. Empty for a terminal service (e.g. the
    # last stage). Used to compute cumulative (end-to-end) latency up to a
    # given service -- see necessity_checker.py.
    next_services: list[str] = Field(default_factory=list)


# Discrete set of KPIs / units the LLM may choose from, so it can't hallucinate
# free-form values. Extend these lists deliberately if a new KPI or unit is
# needed.
KpiType = Literal["cpu", "ram", "latency", "energy", "bandwidth", "storage", "network_in", "network_out"]
Unit = Literal["vCPU", "GB", "MB", "ms", "W", "Mbps", "%"]


class ExtractedRequirement(BaseModel):
    """Requirement fields the LLM is asked to fill via structured output.

    requirement_id is intentionally excluded: it must be assigned
    deterministically by code (incremented as requirements come in), not
    generated by the model.
    """

    kpi_type: KpiType = Field(description="KPI targeted by the requirement")
    comparator: Literal["gte", "lte", "eq"] = Field(description="Comparison operator applied to target_value")
    target_value: float = Field(description="Numeric threshold for the KPI")
    unit: Unit = Field(description="Unit of target_value")
    service: str = Field(description="service_id of the affected service")
    source_span: str = Field(description="Exact excerpt from the source text expressing this requirement")


class ExtractedRequirementList(BaseModel):
    """Wrapper schema used to request a list of requirements via structured output."""

    requirements: list[ExtractedRequirement]


class Requirement(ExtractedRequirement):
    """Structured requirement extracted from a natural-language intent, with a
    deterministic requirement_id assigned by code."""

    requirement_id: str = Field(description="Unique identifier, e.g. 'req-001'")


class NecessityCheckResult(BaseModel):
    status: Literal["reconfiguration_required", "no_action_needed"]
    violated_requirements: list[str]
    services_to_reconsider: list[str]


class DecisionResult(BaseModel):
    decision: dict[str, str]  # service_id -> new node_id
    eligible_nodes_considered: list[str]
    requirements_satisfied: list[str]
    new_configuration: dict[str, str]  # service_id -> node_id (full state)
    # Human-readable (ok/reason) trace of every check performed against the
    # chosen placement -- see utils/csp_checks.py.
    resolution_trace: list[str] = Field(default_factory=list)
    # Trace of the search process itself (candidates tried, improvements
    # found) -- see utils/csp_solver.py:solve_placement.
    search_trace: list[str] = Field(default_factory=list)
