"""Domain schemas shared across the pipeline."""

from typing import Literal

from pydantic import BaseModel, Field


class Node(BaseModel):
    node_id: str
    node_name: str
    tier: Literal["iot", "edge", "fog", "cloud"]
    node_type: str
    cpu_cores: int
    cpu_freq_ghz: float
    ram_gb: int
    storage_gb: int
    mobility: Literal["static", "mobile"]


class Link(BaseModel):
    link_id: str
    source_node: str
    target_node: str
    link_type: str
    bandwidth_mbps: int
    latency_ms: float
    packet_loss_rate: float
    reliability: float


class Service(BaseModel):
    service_id: str
    name: str
    description: str
    current_node: str
    # Static resource footprint this service reserves on current_node, keyed
    # like Node's fields ("cpu_cores", "ram_gb") -- see necessity_checker.py.
    requirements: dict[str, float] | None = None
    # Optional processing time (ms) this service adds to any flow it's part
    # of -- None/absent means 0, additive and backward-compatible (the toy
    # example and ENACT scenario don't declare it). See pipeline.py:flow_latency_ms.
    wcet_ms: float | None = None
    # Optional size (abstract unit matching Link.bandwidth_mbps) of the data
    # this service sends downstream -- when set, the hop to its successor in
    # a flow is costed as ceil(output_size / link.bandwidth_mbps) instead of
    # the link's static latency_ms. None/absent keeps the static-latency
    # model (the toy example and ENACT scenario don't declare it).
    output_size: float | None = None


class Flow(BaseModel):
    """A directed, ordered chain of services forming one logical dataflow
    through the application (e.g. capture -> detection -> alert). Several
    flows may share services at their endpoints without that being a "merge"
    at the flow level -- each flow is independently a simple path, so there
    is never more than one predecessor/successor *within* a given flow.
    Latency (cumulative_flow_latency_ms) is always computed by walking path,
    never stored -- see utils/pipeline.py.
    """

    flow_id: str
    name: str
    description: str
    path: list[str]  # service_ids, in order, root -> terminal
    # Static baseline/contracted requirement for this flow (e.g. {"latency": 40.0}
    # as an initial E2E ceiling), analogous to Service.requirements -- distinct
    # from the actual latency, which is always computed dynamically.
    requirements: dict[str, float] | None = None


class Application(BaseModel):
    application_id: str
    name: str
    flows: list[Flow]


# Discrete set of KPIs / units the LLM may choose from, so it can't hallucinate
# free-form values. Extend these lists deliberately if a new KPI or unit is
# needed.
KpiType = Literal["cpu", "ram", "latency"]
Unit = Literal["vCPU", "GB", "ms"]
TargetType = Literal["service", "flow"]


class ExtractedRequirement(BaseModel):
    """Requirement fields the LLM is asked to fill via structured output.

    requirement_id is intentionally excluded: it must be assigned
    deterministically by code (incremented as requirements come in), not
    generated by the model.
    """

    kpi_type: KpiType = Field(description="KPI targeted by the requirement")
    comparator: Literal["gte", "lte", "eq"] = Field(description="Comparison operator applied to target_value")
    target_value: float = Field(description="Numeric threshold for the KPI")
    unit: Unit = Field(description="Unit of target_value")
    target_type: TargetType = Field(description="Whether the requirement targets a single service or a flow")
    target_id: str = Field(description="service_id (if target_type=service) or flow_id (if target_type=flow)")
    source_span: str = Field(description="Exact excerpt from the source text expressing this requirement")


class ExtractedRequirementList(BaseModel):
    """Wrapper schema used to request a list of requirements via structured output."""

    requirements: list[ExtractedRequirement]


class Requirement(ExtractedRequirement):
    """Structured requirement extracted from a natural-language intent, with a
    deterministic requirement_id assigned by code."""

    requirement_id: str = Field(description="Unique identifier, e.g. 'req-001'")


class NecessityCheckResult(BaseModel):
    status: Literal["reconfiguration_required", "no_action_needed"]
    violated_requirements: list[str]
    services_to_reconsider: list[str]


class DecisionResult(BaseModel):
    # FEASIBLE: a valid placement was found (decision may still be empty if
    # the search converged back to the current one). INFEASIBLE: no
    # candidate placement satisfies every constraint -- see
    # utils/csp_solver.py:solve_placement / decision_engine_cp_sat.py.
    outcome: Literal["FEASIBLE", "INFEASIBLE"] = "FEASIBLE"
    decision: dict[str, str]  # service_id -> new node_id
    eligible_nodes_considered: list[str]
    requirements_satisfied: list[str]
    new_configuration: dict[str, str]  # service_id -> node_id (full state)
    # Human-readable (ok/reason) trace of every check performed against the
    # chosen placement -- see utils/csp_checks.py.
    resolution_trace: list[str] = Field(default_factory=list)
    # Trace of the search process itself (candidates tried, improvements
    # found) -- see utils/csp_solver.py:solve_placement.
    search_trace: list[str] = Field(default_factory=list)
